### ISSUE TITLE
TypeError: save_training_state() takes 3 positional arguments but 4 were given

### ISSUE THREAD

**Issue by eeerpjw** [LiuYunlong99/RQ-LLIE#3]
Besides issue #2 , there is a bug in [train.py/Line:358](https://github.com/LiuYunlong99/RQ-LLIE/blob/585e5b5471b3cef44e82986037e9e0b559b3c059/train.py#L358)

```bash
File "train.py", line 372, in <module>
    main()
  File "train.py", line 359, in main
    model.save_training_state(epoch, current_step,'latest')
TypeError: save_training_state() takes 3 positional arguments but 4 were given
```

I tried to change`model.save_training_state(epoch, current_step,'latest')` to `model.save_training_state(epoch, current_step)` according to the defination of save_training_state().

**Comment by LiuYunlong99** [comment]
Thank you for your feedback on this project!
In the initial training code, line 358 in train.py is model.save_training_state(epoch, 'latest'). I intend to save memory and only keep the latest training state.
