### ISSUE TITLE
您好，请问网络输入大小为(600,400,3)的图片时，参数量和浮点运算量分别是多少？

### ISSUE THREAD

**Issue by lixiaofang-96** [LiuYunlong99/RQ-LLIE#4]
您好，请问如何计算网络的参数量和浮点运算量。

**Comment by LiuYunlong99** [comment]
可以使用fvcore.nn.FlopCountAnalysis统计网络的参数量和计算量

**Comment by lixiaofang-96** [comment]
很感谢您的回复，我在用thop计算时遇到了如下问题，请问这是什么原因。
Traceback (most recent call last):
  File "/home/www/Desktop/code 快捷方式/Retinex/RQ-LLIE-main/test_LOLv1_v2_real.py", line 155, in <module>
    main()
  File "/home/www/Desktop/code 快捷方式/Retinex/RQ-LLIE-main/test_LOLv1_v2_real.py", line 86, in main
    model.test()
  File "/media/www/14F492BBF4929F14/lixiaofang/study/code/Retinex/RQ-LLIE-main/models/model.py", line 173, in test
    Decom_net_macs, Decom_net_params = profile(self.netG.to(device), inputs=(self.var_L.to(device),))
  File "/home/www/anaconda3/envs/pytorch/lib/python3.6/site-packages/thop/profile.py", line 212, in profile
    model(*inputs)
  File "/home/www/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/modules/module.py", line 1102, in _call_impl
    return forward_call(*input, **kwargs)
  File "/home/www/anaconda3/envs/pytorch/lib/python3.6/site-packages/torch/nn/parallel/data_parallel.py", line 156, in forward
    "them on device: {}".format(self.src_device_obj, t.device))
RuntimeError: module must have its parameters and buffers on device cuda:0 (device_ids[0]) but found one of them on device: cpu
我对应的代码是在model.py里的test函数里统计的，具体如下：
 def test(self):
        self.netG.eval()
        with torch.no_grad():
            if self.stage == 0:
                ans = self.netG(self.real_H)
                self.fake_H = ans[0]
            elif self.stage == 1:
                ans =self.netG(self.var_L)
                self.fake_H = ans[0]
            elif self.stage == 2:
                self.fake_H = self.netG(self.var_L)
                print(self.var_L)
                print(self.netG)
                Decom_net_macs, Decom_net_params = profile(self.netG.to(device), inputs=(self.var_L.to(device),))
                Decom_net_macs, Decom_net_params = clever_format([Decom_net_macs, Decom_net_params], "%.5f")
                print(Decom_net_macs, Decom_net_params)
            else:
                raise NotImplementedError()
        self.netG.train()
其中device = torch.device('cuda:0' if torch.cuda.is_available() else 'cpu')。

**Comment by LiuYunlong99** [comment]
可以在models/arch/network.py最后添加以下代码：
```
if __name__ == '__main__':
    with torch.no_grad():
        from fvcore.nn import FlopCountAnalysis
        model = Network(stage=2).cuda()
        model.set_query_codebook()
        inputs = torch.randn((1, 3, 400, 600)).cuda()
        flops = FlopCountAnalysis(model, inputs)
        n_param = sum([p.nelement() for p in model.parameters()])  # 所有参数数量
        print(f'GMac:{flops.total() / (1024 * 1024 * 1024)}')
        print(f'Params:{n_param / 1e6:.2f} Mb')
```
然后运行models/arch/network.py，即可得到参数量和计算量！
如果我们的工作对您有所帮助，麻烦您帮我们点一下star！

**Comment by lixiaofang-96** [comment]
好的，非常感谢
